spring:
  application:
    name: spring-boot-assessment
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    active:
    - db

